/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#ffffff",
        "surface-tint": "#1b6d24",
        "on-secondary-fixed-variant": "#004a75",
        "inverse-primary": "#88d982",
        "on-primary-fixed-variant": "#005312",
        "on-surface": "#191c1d",
        "on-primary": "#ffffff",
        "secondary-container": "#51b2fe",
        "on-primary-container": "#cbffc2",
        "surface-container-low": "#f3f4f5",
        "background": "#f8f9fa",
        "tertiary-fixed": "#ffddb8",
        "on-primary-fixed": "#002204",
        "on-secondary": "#ffffff",
        "primary-fixed": "#a3f69c",
        "on-surface-variant": "#40493d",
        "secondary-fixed": "#cee5ff",
        "inverse-on-surface": "#f0f1f2",
        "inverse-surface": "#2e3132",
        "on-secondary-fixed": "#001d32",
        "primary-fixed-dim": "#88d982",
        "on-tertiary-container": "#ffeedf",
        "primary-container": "#2e7d32",
        "surface-bright": "#f8f9fa",
        "tertiary": "#794b00",
        "secondary-fixed-dim": "#96ccff",
        "primary": "#0d631b",
        "outline": "#707a6c",
        "surface-container-lowest": "#ffffff",
        "on-background": "#191c1d",
        "surface-variant": "#e1e3e4",
        "tertiary-fixed-dim": "#ffb95f",
        "surface-container": "#edeeef",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-tertiary-fixed-variant": "#653e00",
        "secondary": "#00639a",
        "surface-container-high": "#e7e8e9",
        "surface-dim": "#d9dadb",
        "on-error-container": "#93000a",
        "error": "#ba1a1a",
        "on-tertiary-fixed": "#2a1700",
        "on-secondary-container": "#00436a",
        "tertiary-container": "#9a6100",
        "surface-container-highest": "#e1e3e4",
        "surface": "#f8f9fa",
        "outline-variant": "#bfcaba"
      },
      spacing: {
        "sm": "12px",
        "gutter": "24px",
        "base": "8px",
        "md": "24px",
        "xl": "64px",
        "margin-mobile": "16px",
        "xs": "4px",
        "lg": "40px",
        "margin-desktop": "32px",
        "container-max": "1200px"
      },
      fontFamily: {
        "headline-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }]
      }
    },
  },
  plugins: [],
}